name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        if: success()
        uses: umuttopalak/pythonanywhere-deploy-action@v1.1.0
        with:
          host: 'www.pythonanywhere.com'
          username: 'ricardosalimd'
          api_token: 'edb0d1413f54a67a909ff7d5c88e06a59b27efb2'
          domain_name: 'https://ricardosalimd.pythonanywhere.com/'