# Generated by Django 5.1.6 on 2025-02-13 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0006_productsbycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=8, verbose_name='CEP')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('password', models.CharField(max_length=100, verbose_name='Senha')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='Número do Cartão')),
                ('card_holder', models.CharField(max_length=100, verbose_name='Nome no Cartão')),
                ('card_expiration_date', models.DateField(verbose_name='Data de Validade')),
                ('card_cvv', models.CharField(max_length=3, verbose_name='CVV')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='exclusive_api.user', verbose_name='Usuário')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupom_code', models.CharField(blank=True, max_length=100, verbose_name='Cupom')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('billing_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='exclusive_api.billinginfo', verbose_name='Informações de Faturamento')),
                ('products', models.ManyToManyField(related_name='pedidos', to='exclusive_api.product', verbose_name='Produtos')),
                ('payment_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='exclusive_api.paymentinfo', verbose_name='Informações de Pagamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='exclusive_api.user', verbose_name='Usuário')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturamentos', to='exclusive_api.user', verbose_name='Usuário'),
        ),
        migrations.DeleteModel(
            name='ProductsByCategory',
        ),
    ]
