# Generated by Django 5.1.6 on 2025-02-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0007_billinginfo_user_paymentinfo_order_billinginfo_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentinfo',
            options={'ordering': ['user', 'card_number', 'card_holder', 'card_expiration_date', 'card_cvv']},
        ),
    ]
