# Generated by Django 5.1.6 on 2025-02-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0008_alter_paymentinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billinginfo',
            options={'ordering': ['user', 'address', 'complement', 'city', 'state', 'zip_code']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
