# Generated by Django 5.1.6 on 2025-02-19 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0010_alter_billinginfo_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Avaliação'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Tamanho'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nome')),
                ('image', models.ImageField(upload_to='products', verbose_name='Imagem')),
                ('url', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='URL')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='exclusive_api.product', verbose_name='Produto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
