# Generated by Django 5.1.6 on 2025-02-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0011_product_color_product_rating_product_size_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='products/', verbose_name='Imagem'),
        ),
    ]
