# Generated by Django 5.1.6 on 2025-02-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0012_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
