# Generated by Django 5.1.6 on 2025-03-03 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0013_remove_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='wishlists', to='exclusive_api.product', verbose_name='Produtos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='exclusive_api.user', verbose_name='Usuário')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
