# Generated by Django 5.1.6 on 2025-03-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0015_remove_wishlist_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='wishlists', to='exclusive_api.product', verbose_name='Produtos'),
        ),
    ]
