# Generated by Django 5.1.6 on 2025-03-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0016_wishlist_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nome')),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='categories/', verbose_name='Imagem')),
                ('category', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='exclusive_api.category', verbose_name='Categoria')),
            ],
            options={
                'ordering': ['id', 'category', 'image'],
            },
        ),
    ]
