# Generated by Django 5.1.6 on 2025-03-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0020_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories_list',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Categorias'),
        ),
    ]
