# Generated by Django 5.1.6 on 2025-03-28 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0022_remove_product_categories_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='exclusive_api.product', verbose_name='Produto'),
        ),
    ]
