# Generated by Django 5.2 on 2025-04-24 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0023_alter_image_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Marca')),
            ],
            options={
                'ordering': ['id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='exclusive_api.brand', verbose_name='Marca'),
        ),
    ]
