# Generated by Django 5.2 on 2025-04-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0024_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
    ]
