# Generated by Django 5.2 on 2025-04-24 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0025_product_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Review')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='exclusive_api.product', verbose_name='Produto')),
            ],
            options={
                'ordering': ['id', 'review_text'],
            },
        ),
    ]
