# Generated by Django 5.2 on 2025-04-26 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0026_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Produto Ativo'),
        ),
        migrations.AddField(
            model_name='product',
            name='bestSelling',
            field=models.BooleanField(default=False, verbose_name='Destaque de Vendas'),
        ),
        migrations.AddField(
            model_name='product',
            name='flashSales',
            field=models.BooleanField(default=False, verbose_name='Promoção de Vendas'),
        ),
        migrations.AddField(
            model_name='product',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='Produto de Destaque'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Tag')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='exclusive_api.product', verbose_name='Produto')),
            ],
            options={
                'ordering': ['id', 'name'],
            },
        ),
    ]
