# Generated by Django 5.2 on 2025-04-26 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0027_product_active_product_bestselling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='exclusive_api.tag', verbose_name='Tag'),
        ),
    ]
