# Generated by Django 5.2 on 2025-04-26 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0029_remove_product_tags_tag_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='exclusive_api.brand', verbose_name='Marca'),
        ),
    ]
