# Generated by Django 5.2 on 2025-04-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0030_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
