# Generated by Django 5.2 on 2025-04-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0032_product_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='produtos', to='exclusive_api.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='exclusive_api.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Tag'),
        ),
    ]
