# Generated by Django 5.2 on 2025-04-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0035_alter_product_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Marca'),
        ),
    ]
