# Generated by Django 5.2 on 2025-04-26 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0036_alter_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
