# Generated by Django 5.2 on 2025-04-26 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0037_remove_product_brands_remove_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='exclusive_api.brand', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='produtos', to='exclusive_api.tag', verbose_name='Tags'),
        ),
    ]
