# Generated by Django 5.2 on 2025-04-26 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0038_product_brands_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.AddField(
            model_name='brand',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='exclusive_api.product', verbose_name='Produto'),
        ),
    ]
