# Generated by Django 5.2 on 2025-04-26 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0039_rename_product_review_products_remove_product_brands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='exclusive_api.brand', verbose_name='Marca'),
        ),
    ]
