# Generated by Django 5.2 on 2025-04-26 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0040_remove_brand_products_product_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='exclusive_api.brand', verbose_name='Marca'),
        ),
    ]
