# Generated by Django 5.2 on 2025-04-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0041_alter_product_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
    ]
