# Generated by Django 5.2 on 2025-04-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0043_product_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='products',
        ),
    ]
