# Generated by Django 5.2 on 2025-04-26 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0044_remove_review_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='products',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='exclusive_api.product', verbose_name='Produto'),
        ),
    ]
