# Generated by Django 5.2 on 2025-04-26 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0046_alter_product_brands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brands',
            new_name='brand',
        ),
    ]
