# Generated by Django 5.2 on 2025-04-26 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0047_rename_brands_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='sizes',
        ),
    ]
