# Generated by Django 5.2 on 2025-04-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0049_rename_color_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isNew',
            field=models.BooleanField(default=False, verbose_name='Produto Novo'),
        ),
    ]
