# Generated by Django 5.2 on 2025-04-26 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive_api', '0050_product_isnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='products',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='exclusive_api.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(default='', max_length=300, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Tag'),
        ),
    ]
